#server:
#  port: 8080
#  servlet:
#    context-path: /seckill
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.majianbo.seckill.entity
logging:
  level.cn.majianbo.seckill.dao: trace
  path: logs/
  file: log.log
